# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import hybridstream_pb2 as hybridstream__pb2


class HEAManagementStub(object):
    """─────────────────────────────────────────────────
    Service definition — same 4 RPCs on HEA and Flink Connector
    ─────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTelemetry = channel.unary_unary(
                '/hybridstream.v1.HEAManagement/GetTelemetry',
                request_serializer=hybridstream__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.TelemetryResponse.FromString,
                )
        self.ApplyPlacement = channel.unary_unary(
                '/hybridstream.v1.HEAManagement/ApplyPlacement',
                request_serializer=hybridstream__pb2.PlacementDirective.SerializeToString,
                response_deserializer=hybridstream__pb2.PlacementAck.FromString,
                )
        self.TriggerSnapshot = channel.unary_unary(
                '/hybridstream.v1.HEAManagement/TriggerSnapshot',
                request_serializer=hybridstream__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.SnapshotResponse.FromString,
                )
        self.TerminateOperator = channel.unary_unary(
                '/hybridstream.v1.HEAManagement/TerminateOperator',
                request_serializer=hybridstream__pb2.TerminateRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.TerminateAck.FromString,
                )


class HEAManagementServicer(object):
    """─────────────────────────────────────────────────
    Service definition — same 4 RPCs on HEA and Flink Connector
    ─────────────────────────────────────────────────

    """

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPlacement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateOperator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HEAManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=hybridstream__pb2.TelemetryRequest.FromString,
                    response_serializer=hybridstream__pb2.TelemetryResponse.SerializeToString,
            ),
            'ApplyPlacement': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPlacement,
                    request_deserializer=hybridstream__pb2.PlacementDirective.FromString,
                    response_serializer=hybridstream__pb2.PlacementAck.SerializeToString,
            ),
            'TriggerSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSnapshot,
                    request_deserializer=hybridstream__pb2.SnapshotRequest.FromString,
                    response_serializer=hybridstream__pb2.SnapshotResponse.SerializeToString,
            ),
            'TerminateOperator': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateOperator,
                    request_deserializer=hybridstream__pb2.TerminateRequest.FromString,
                    response_serializer=hybridstream__pb2.TerminateAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hybridstream.v1.HEAManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HEAManagement(object):
    """─────────────────────────────────────────────────
    Service definition — same 4 RPCs on HEA and Flink Connector
    ─────────────────────────────────────────────────

    """

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.HEAManagement/GetTelemetry',
            hybridstream__pb2.TelemetryRequest.SerializeToString,
            hybridstream__pb2.TelemetryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyPlacement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.HEAManagement/ApplyPlacement',
            hybridstream__pb2.PlacementDirective.SerializeToString,
            hybridstream__pb2.PlacementAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.HEAManagement/TriggerSnapshot',
            hybridstream__pb2.SnapshotRequest.SerializeToString,
            hybridstream__pb2.SnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TerminateOperator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.HEAManagement/TerminateOperator',
            hybridstream__pb2.TerminateRequest.SerializeToString,
            hybridstream__pb2.TerminateAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AODEManagementStub(object):
    """─────────────────────────────────────────────────
    AODEManagement — external management API
    ─────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/hybridstream.v1.AODEManagement/GetStatus',
                request_serializer=hybridstream__pb2.AODEStatusRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.AODEStatusResponse.FromString,
                )
        self.TriggerRecalibration = channel.unary_unary(
                '/hybridstream.v1.AODEManagement/TriggerRecalibration',
                request_serializer=hybridstream__pb2.RecalibrationRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.RecalibrationResponse.FromString,
                )
        self.UpdateWeights = channel.unary_unary(
                '/hybridstream.v1.AODEManagement/UpdateWeights',
                request_serializer=hybridstream__pb2.WeightUpdateRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.WeightUpdateResponse.FromString,
                )
        self.GetPlacementState = channel.unary_unary(
                '/hybridstream.v1.AODEManagement/GetPlacementState',
                request_serializer=hybridstream__pb2.PlacementStateRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.PlacementStateResponse.FromString,
                )


class AODEManagementServicer(object):
    """─────────────────────────────────────────────────
    AODEManagement — external management API
    ─────────────────────────────────────────────────

    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerRecalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlacementState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AODEManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=hybridstream__pb2.AODEStatusRequest.FromString,
                    response_serializer=hybridstream__pb2.AODEStatusResponse.SerializeToString,
            ),
            'TriggerRecalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRecalibration,
                    request_deserializer=hybridstream__pb2.RecalibrationRequest.FromString,
                    response_serializer=hybridstream__pb2.RecalibrationResponse.SerializeToString,
            ),
            'UpdateWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWeights,
                    request_deserializer=hybridstream__pb2.WeightUpdateRequest.FromString,
                    response_serializer=hybridstream__pb2.WeightUpdateResponse.SerializeToString,
            ),
            'GetPlacementState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlacementState,
                    request_deserializer=hybridstream__pb2.PlacementStateRequest.FromString,
                    response_serializer=hybridstream__pb2.PlacementStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hybridstream.v1.AODEManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AODEManagement(object):
    """─────────────────────────────────────────────────
    AODEManagement — external management API
    ─────────────────────────────────────────────────

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.AODEManagement/GetStatus',
            hybridstream__pb2.AODEStatusRequest.SerializeToString,
            hybridstream__pb2.AODEStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerRecalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.AODEManagement/TriggerRecalibration',
            hybridstream__pb2.RecalibrationRequest.SerializeToString,
            hybridstream__pb2.RecalibrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.AODEManagement/UpdateWeights',
            hybridstream__pb2.WeightUpdateRequest.SerializeToString,
            hybridstream__pb2.WeightUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlacementState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.AODEManagement/GetPlacementState',
            hybridstream__pb2.PlacementStateRequest.SerializeToString,
            hybridstream__pb2.PlacementStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FlinkConnectorStub(object):
    """─────────────────────────────────────────────────
    FlinkConnector service (PCTR Phase 3 operations)
    ─────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RestoreOperator = channel.unary_unary(
                '/hybridstream.v1.FlinkConnector/RestoreOperator',
                request_serializer=hybridstream__pb2.RestoreRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.RestoreResponse.FromString,
                )
        self.TerminateOperator = channel.unary_unary(
                '/hybridstream.v1.FlinkConnector/TerminateOperator',
                request_serializer=hybridstream__pb2.TerminateRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.TerminateAck.FromString,
                )
        self.GetJobStatus = channel.unary_unary(
                '/hybridstream.v1.FlinkConnector/GetJobStatus',
                request_serializer=hybridstream__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=hybridstream__pb2.JobStatusResponse.FromString,
                )


class FlinkConnectorServicer(object):
    """─────────────────────────────────────────────────
    FlinkConnector service (PCTR Phase 3 operations)
    ─────────────────────────────────────────────────

    """

    def RestoreOperator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateOperator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlinkConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RestoreOperator': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreOperator,
                    request_deserializer=hybridstream__pb2.RestoreRequest.FromString,
                    response_serializer=hybridstream__pb2.RestoreResponse.SerializeToString,
            ),
            'TerminateOperator': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateOperator,
                    request_deserializer=hybridstream__pb2.TerminateRequest.FromString,
                    response_serializer=hybridstream__pb2.TerminateAck.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=hybridstream__pb2.JobStatusRequest.FromString,
                    response_serializer=hybridstream__pb2.JobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hybridstream.v1.FlinkConnector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlinkConnector(object):
    """─────────────────────────────────────────────────
    FlinkConnector service (PCTR Phase 3 operations)
    ─────────────────────────────────────────────────

    """

    @staticmethod
    def RestoreOperator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.FlinkConnector/RestoreOperator',
            hybridstream__pb2.RestoreRequest.SerializeToString,
            hybridstream__pb2.RestoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TerminateOperator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.FlinkConnector/TerminateOperator',
            hybridstream__pb2.TerminateRequest.SerializeToString,
            hybridstream__pb2.TerminateAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hybridstream.v1.FlinkConnector/GetJobStatus',
            hybridstream__pb2.JobStatusRequest.SerializeToString,
            hybridstream__pb2.JobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
